import React from "react";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Head from "next/head";

const Ideas = () => {
  return (
    <div>
      <Head>
        <title>Flights Blog | Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex h-[36rem] bg-[#fec144] justify-center md:rounded-br-full">
        <div className="flex flex-col md:flex-row justify-center items-center">
          <img
            src="./map.jpg"
            className="h-3/5 md:h-4/5 w-full md:w-2/5 md:mr-8 object-cover"
          />
          <div
            className="w-full md:w-2/5 text-center md:text-left
          self-stretch h-4/5 my-auto"
          >
            <h3 className="text-3xl mb-2">Travel Ideas</h3>
            <h4 className="font-bold text-[20px]">
              You must visit these places!
            </h4>
            <p className="text-[18px]">
              It's time to choose new destinations worth visiting, and the
              annual National Geographic ranking is an irreplaceable source of
              inspiration! Many places that appeared on the list may surprise
              you and certainly encourage you to travel different than before.
              From the list of 28 directions presented by the magazine, we have
              selected the 10 most interesting for you. Ready to go on a
              journey?
            </p>
          </div>
        </div>
      </div>
      <div className="flex flex-col items-center max-w-7xl mx-auto mt-28 text-[18px] p-[10px]">
        <div className="flex flex-col md:flex-row items-center md:items-start  mt-5 md:mt-0">
          <img src="./mexico.jpg" alt="mexico img" className="w-3/4 md:w-1/2" />
          <div className="md:ml-5 mt-3 md:mt-0 w-full md:w-1/2 text-center">
            <h2 className="font-bold text-[20px] mb-2">
              1. Mexico City, Meksyk
            </h2>
            <p>
              Why? Because of the great kitchen! Of course, corn reigns supreme
              here. The golden grain trend has returned and now thousands of
              variations of different dishes are being created: from tortillas
              with local types of corn, maize seasoned with saffron, served with
              stewed beans, to chocolate-corn smoothies. Interesting and
              delicious!
            </p>
          </div>
        </div>
        <div className="flex flex-col-reverse md:flex-row items-center md:items-start mt-5 md:mt-0">
          <div className="md:mr-5 w-full md:w-1/2 mt-3 text-center">
            <h2 className="font-bold text-[20px] mb-2">2. Dakar, Senegal </h2>
            <p>
              Why? Lush life and a rich culture are the hallmarks of Dakar. It
              will charm you with beautiful beaches, surfers, colorful
              supermarkets and wild sheep. Nightlife is also booming: discover
              mbalax dance, the Senegalese hip hop scene, street art and the
              Dakar Fashion Week. You won't get bored here!
            </p>
          </div>
          <img src="./china.jpg" alt="senegal img" className="w-3/4 md:w-1/2" />
        </div>
        <div className="flex flex-col md:flex-row items-center md:items-start  mt-5 md:mt-0">
          <img src="./senegal.jpg" alt="china img" className="w-3/4 md:w-1/2" />
          <div className="md:ml-5 w-full md:w-1/2 mt-3 text-center">
            <h2 className="font-bold text-[20px] mb-2">
              3. Fanjingshan Mountains, China
            </h2>
            <p>
              Why? It's really an unknown direction, and it has already landed
              on UNESCO list. There are 48 temples there and he is a saint
              Buddhist place. The surroundings are also amazing rock formations
              and nature - protected species live here animals, including rare
              species of monkeys.
            </p>
          </div>
        </div>
        <div className="flex flex-col-reverse md:flex-row items-center md:items-start mt-5 md:mt-0">
          <div className="md:ml-5 w-full md:w-1/2 mt-3 text-center">
            <h2 className="font-bold text-[20px] mb-2">4. Greenland</h2>
            <p>
              Why? For an unforgettable adventure! Greenland is the largest
              island in the world and over 80% of its surface is covered by ice.
              You cannot complain about boredom there and you can choose between
              attractions such as discovering the fjords, a helicopter flight
              over the glaciers or dog sledding. In addition, beautiful natural
              phenomena such as the northern lights or the midnight sun.
            </p>
          </div>
          <img
            src="./greenland.jpg"
            alt="greenland img"
            className="w-3/4 md:w-1/2"
          />
        </div>
        <div className="flex flex-col md:flex-row items-center md:items-start  mt-5 md:mt-0">
          <img
            src="./vietnam.jpg"
            alt="vietnam img"
            className="w-3/4 md:w-1/2"
          />
          <div className="md:ml-5 w-full md:w-1/2 mt-3 text-center">
            <h2 className="font-bold text-[20px] mb-2">
              5. Hoang Lien Son, Vietnam
            </h2>
            <p>
              Why? Amazing nature and tribal cultures! Located in northeastern
              Vietnam, the Hoang Lien Son National Park and the Muong Hoa Valley
              are places little known to tourists. We will reach the highest
              peak in the region, Phan Xi Pang, by cable car. In addition, the
              opportunity to spend the night with the Hmong, Dao, Tay or Giay
              ethnic groups is an interesting experience and an unprecedented
              opportunity to learn about their traditions.
            </p>
          </div>
        </div>
        <div className="flex flex-col-reverse md:flex-row items-center md:items-start mt-5 md:mt-0">
          <div className="md:ml-5 w-full md:w-1/2 mt-3 text-center">
            <h2 className="font-bold text-[20px] mb-2">
              6. Bisti Reserve / De-Na-Zin, USA
            </h2>
            <p>
              Why? To get away from everyday life! Few tourists know these
              regions, and the entire reserve is a truly unique place. Lunar
              views, hiking in the desert - the perfect place to go communing
              with oneself.
            </p>
          </div>
          <img src="./usa.jpg" alt="usa img" className="w-3/4 md:w-1/2" />
        </div>
        <div className="flex flex-col md:flex-row items-center md:items-start  mt-5 md:mt-0">
          <img src="./oman.jpg" alt="oman img" className="w-3/4 md:w-1/2" />
          <div className="md:ml-5 w-full md:w-1/2 mt-3 text-center">
            <h2 className="font-bold text-[20px] mb-2">7. Oman</h2>
            <p>
              Why? Not every country has attractions such as a ride on a
              thoroughbred horse and discovering such places country like the
              Hajar mountains, the winding gorges of Wadi an Nakhur, the beaches
              of the Gulf Oman or the red dunes of Rub al Khali. Oman promotes
              in equestrian traditions in recent years and aims to restore them.
              And visitors can experience something under the watchful eye of
              professional riders amazing and cross this beautiful country on a
              horseback.
            </p>
          </div>
        </div>
        <div className="flex flex-col-reverse md:flex-row items-center md:items-start mt-5 md:mt-0">
          <div className="md:ml-5 w-full md:w-1/2 mt-3 text-center">
            <h2 className="font-bold text-[20px] mb-2">8. Toronto, Canada</h2>
            <p>
              Why? You will meet incredible cultural diversity here - more than
              half of Toronto's inhabitants are immigrants. Over 200 languages
              ​​can be heard on the streets of this colorful city, which is
              teeming with concerts, festivals, art and street life. You will
              not be bored here, as there are as many as 140 districts waiting
              for you to discover.
            </p>
          </div>
          <img src="./canada.jpg" alt="canada img" className="w-3/4 md:w-1/2" />
        </div>
        <div className="flex flex-col md:flex-row items-center md:items-start  mt-5 md:mt-0">
          <img src="./belize.jpg" alt="canada img" className="w-3/4 md:w-1/2" />
          <div className="md:ml-5 w-full md:w-1/2 mt-3 text-center">
            <h2 className="font-bold text-[20px] mb-2">9. Belize</h2>
            <p>
              Why? It is an extremely rich place on earth that also places
              emphasis on nature conservation. The Great Barrier Reef of Belize
              has even been removed from UNESCO's list of endangered sites. The
              reef is one of the richest places on earth and home to many rare
              and endangered species. In addition, in Belize you can visit
              important Mayan centers such as Caracol.
            </p>
          </div>
        </div>
        <div className="flex flex-col-reverse md:flex-row items-center md:items-start mt-5 md:mt-0">
          <div className="md:mr-5 w-full md:w-1/2 mt-3 text-center">
            <h2 className="font-bold text-[20px] mb-2">10. Montenegro</h2>
            <p>
              Why? If you like nature and hiking, that's why. This small Balkan
              country has many natural treasures yet undiscovered by tourists,
              including the Bay of Kotor, which is on the UNESCO list. There are
              many activities to choose from: rafting, hiking, river rafting,
              bicycles. There will also be plenty of opportunities for
              sunbathing and bathing, because Montenegro has beautiful lakes,
              rivers and access to the Adriatic Sea.
            </p>
          </div>
          <img
            src="./montenegro.jpg"
            alt="montenegro img"
            className="w-3/4 md:w-1/2"
          />
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default Ideas;
