export const wordList = {
  a: [
    "abuja",
    "accra",
    "alofi",
    "amman",
    "alamo",
    "avian",
    "aztec",
    "aruba",
    "atlas",
  ],
  b: [
    "benin",
    "basel",
    "brest",
    "berne",
    "bursa",
    "bryne",
    "braga",
    "banff",
    "beach",
    "birma",
    "blanc"
  ],
  c: [
    "chile",
    "china",
    "corfu",
    "cadiz",
    "cairo",
    "cusco",
    "conwy",
    "crete",
    "climb",
    "camel",
    "capri",
    "cocos",
    "czech",
    "croat",
    "congo",
    "cuban"
  ],
  d: [
    "dijon",
    "dakar",
    "dhaka",
    "delhi",
    "dubai",
    "dover",
    "derby",
    "derry",
    "digne",
    "drive",
    "delta",
    "dutch",
    "dnepr",
    "denar",
    "dinar",
    "ducat",
  ],
  e: ["egypt", "essen", "essex", "espoo", "elche", "eilat", "epcot", "earth"],
  f: ["fargo", "fjord", "furth", "ferry", "franc"],
  g: ["ghana", "gabon", "genoa", "ghent", "gijon", "globe", "greek"],
  h: ["haiti", "hanoi", "haifa", "hamar", "hindi", "hijab"],
  i: ["india", "italy", "izmir", "ibiza", "idaho", "irish", "indus", "islam","iraqi"],
  j: ["japan", "jaffa"],
  k: [
    "kenya",
    "kazan",
    "kolin",
    "kabul",
    "kyoto",
    "kotor",
    "krabi",
    "kayak",
    "krone",
    "krona",
  ],
  l: [
    "libya",
    "liege",
    "lille",
    "leeds",
    "luton",
    "lahti",
    "lutsk",
    "lagos",
    "lapaz",
    "lutsk",
    "limon",
    "lecce",
    "larne",
    "ladin",
    "loire",
    "livre",
  ],
  m: [
    "malta",
    "minsk",
    "malmo",
    "milan",
    "molde",
    "mainz",
    "macau",
    "miami",
    "macon",
    "mecca",
    "maine",
    "manta",
  ],
  n: ["nauru", "nepal", "niger", "nimes", "nancy"],
  o: ["osaka", "omaha","omani"],
  p: [
    "palau",
    "paris",
    "porto",
    "plzen",
    "praia",
    "parma",
    "padua",
    "petra",
    "parnu",
    "perth",
    "pekin",
    "praha",
    "pound",
    "penny",
    "poles"
  ],
  q: ["qatar", "quito"],
  r: ["reims", "rabat", "ruins", "rodeo", "rhine", "ruble", "rupee"],
  s: [
    "samoa",
    "syria",
    "split",
    "sudan",
    "spain",
    "sofia",
    "sochi",
    "seoul",
    "sucre",
    "sanaa",
    "sopot",
    "shamu",
    "sight",
    "stoke",
    "suomi",
    "sakai",
    "sinai",
    "stone",
    "swiss",
    "swazi"
  ],
  t: [
    "tonga",
    "turin",
    "turku",
    "torun",
    "tokyo",
    "tunis",
    "tychy",
    "tampa",
    "tulsa",
    "tulum",
    "tahoe",
    "tomsk",
    "texas",
    "terra",
    "tatar",
    "tiber",
    "taler",
    "tajik"
  ],
  u: ["uzbek"],
  v: ["varna", "vaduz", "vaxjo", "volta", "volga"],
  w: ["wigan", "wells", "wuhan", "wesel", "world", "wales", "welsh", "warta"],
  y: ["yemen", "yaren", "ystad", "yacht", "yukon"],
  z: ["zadar", "zloty"],
};
